par <- setPar("nba",2011)
nba.raw <- formatNBAdata()
nba.tf <- calcTF(nba.raw$Totals,nba.raw$Team.Opp[nba.raw$Team.Opp$Team.Opp=="Team","G"])
nba.vc <- calcVC(nba.tf,nba.raw)
updateWebsite(nba.raw,nba.tf,nba.vc)
