par <- setPar("ncaa", 2017)
ncaa.raw <- formatNCAAdata()
ncaa.team.raw <- formatNCAAteamData()
ncaa.tf <- calcTF(ncaa.raw, ncaa.team.raw[,"TmG"])
ncaa.vc <- calcVC(ncaa.tf, ncaa.team.raw)
save(ncaa.raw, ncaa.tf, ncaa.vc, ncaa.team.raw, file=paste("data/ncaa/2017/ncaa2017.RData"))
updateWebsite(ncaa.raw, ncaa.tf, ncaa.vc, ncaa.team.raw)
