#!/usr/bin/env python3
"""Usage:
  nbaget <year>

Arguments:
  year      Year that the season ends in; e.g., 2018 for the 2017-2018 season
"""

import os
import docopt
from docopt import docopt
arg = docopt(__doc__)

## y1=second year (i.e. 2010)
## y2=combined years (i.e. 0910)
## y3=first year (i.e. 09)
y1 = arg['<year>']
yy = int(y1[2:4])
y2 = ("%02d" % (yy-1)) + ("%02d" % yy)
y3 = ("%02d" % (yy-1))

def get1(a, b):
    os.system('./brget ' + a + ' ' + b + ' ' + y1)

def get2(a, b):
    os.system('./82get ' + a + ' ' + b + ' ' + y1 + ' ' + y2 + ' ' + y3)

os.system('wget http://www.basketball-reference.com/leagues/NBA_' + y1 + '.html -O ../data/nba/' + y1 + '/raw/nba.html')

get1('BOS', 'bos')
get1('NJN', 'njn')
get1('NYK', 'nyk')
get1('PHI', 'phi')
get1('TOR', 'tor')
get1('CHI', 'chi')
get1('CLE', 'cle')
get1('DET', 'det')
get1('IND', 'ind')
get1('MIL', 'mil')
get1('ATL', 'atl')
get1('CHA', 'cha')
get1('MIA', 'mia')
get1('ORL', 'orl')
get1('WAS', 'was')
get1('DAL', 'dal')
get1('HOU', 'hou')
get1('MEM', 'mem')
get1('NOP', 'nop')
get1('SAS', 'sas')
get1('DEN', 'den')
get1('MIN', 'min')
get1('POR', 'por')
# get1('SEA', 'sea')
get1('OKC', 'okc')
get1('UTA', 'uta')
get1('GSW', 'gsw')
get1('LAC', 'lac')
get1('LAL', 'lal')
get1('PHO', 'pho')
get1('SAC', 'sac')


get2('BOS', 'bos')
get2('NJN', 'njn')
get2('NYK', 'nyk')
get2('PHI', 'phi')
get2('TOR', 'tor')
get2('CHI', 'chi')
get2('CLE', 'cle')
get2('DET', 'det')
get2('IND', 'ind')
get2('MIL', 'mil')
get2('ATL', 'atl')
get2('CHA', 'cha')
get2('MIA', 'mia')
get2('ORL', 'orl')
get2('WAS', 'was')
get2('DAL', 'dal')
get2('HOU', 'hou')
get2('MEM', 'mem')
get2('NOP', 'nop')
get2('SAS', 'sas')
get2('DEN', 'den')
get2('MIN', 'min')
get2('POR', 'por')
# get2('SEA', 'sea')
get2('OKC', 'okc')
get2('UTA', 'uta')
get2('GSW', 'gsw')
get2('LAC', 'lac')
get2('LAL', 'lal')
get2('PHO', 'pho')
get2('SAC', 'sac')
