# First round
ncaag('')
ncaag('')
ncaag('')
ncaag('')
ncaag('')
ncaag('')
ncaag('')
ncaag('')
ncaag('')
ncaag('')

# Second round
ncaag('http://www.sports-reference.com/cbb/boxscores/2016-03-19-kansas.html')
ncaag('http://www.sports-reference.com/cbb/boxscores/2016-03-19-north-carolina.html')
ncaag('http://www.sports-reference.com/cbb/boxscores/2016-03-19-virginia.html')
ncaag('http://www.sports-reference.com/cbb/boxscores/2016-03-19-miami-fl.html')
ncaag('http://www.sports-reference.com/cbb/boxscores/2016-03-19-utah.html')
ncaag('http://www.sports-reference.com/cbb/boxscores/2016-03-19-duke.html')
ncaag('http://www.sports-reference.com/cbb/boxscores/2016-03-19-iowa-state.html')
ncaag('http://www.sports-reference.com/cbb/boxscores/2016-03-19-kentucky.html')
ncaag('http://www.sports-reference.com/cbb/boxscores/2016-03-20-villanova.html')
ncaag('http://www.sports-reference.com/cbb/boxscores/2016-03-20-oregon.html')
ncaag('http://www.sports-reference.com/cbb/boxscores/2016-03-20-oklahoma.html')
ncaag('http://www.sports-reference.com/cbb/boxscores/2016-03-20-xavier.html')
ncaag('http://www.sports-reference.com/cbb/boxscores/2016-03-20-texas-am.html')
ncaag('http://www.sports-reference.com/cbb/boxscores/2016-03-20-maryland.html')
ncaag('http://www.sports-reference.com/cbb/boxscores/2016-03-20-notre-dame.html')
ncaag('http://www.sports-reference.com/cbb/boxscores/2016-03-20-syracuse.html')
